---
driver:
  name: vagrant
  require_chef_omnibus: 11.8

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[exhibitor::default]
      - recipe[exhibitor::service]
    attributes:
