---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[exhibitor::default]
      - recipe[exhibitor::service]

  - name: upstart
    run_list:
      - recipe[exhibitor::default]
      - recipe[exhibitor::service]
    attributes:
      exhibitor:
        service_style: upstart
    excludes:
      - centos-6.6
